apps/academy/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^candidate/$', views.CandidateCreateView.as_view(), name='candidate-new'),

    url(r'^test-list/$', views.TestTestListView.as_view(), name='test-list'),

    url(r'^test/(?P<slug>[a-z0-9_-]+)/$', views.test_detail_view, name='test-detail'),

    url(r'^jedi/$', views.JediListView.as_view(), name='jedi-list'),

    url(r'^candidate/list/(?P<jedi_pk>\d+)/$', views.candidate_list, name='candidate-list'),

    url(r'^candidate/add/$', views.candidate_add, name='candidate-add'),
]

apps/core/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'academy/', include('academy.urls', namespace='academy')),

    url(r'^$', views.HomePage.as_view(), name='home_page'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

apps/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
	{% load static %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" href="http://getbootstrap.com/favicon.ico">

	{% block meta-title %}
		<title>Welcome to Academy!</title>
	{% endblock %}

	{% block meta-tags %}{% endblock %}

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<style>
		body{
			padding-top: 100px;
		}
	</style>
</head>

<body>

{% if messages %}
	<div class="container">
		{% for message in messages %}
			<div class="alert alert-{{ message.tags }}" role="alert">
				<a class="close" href="#" data-dismiss="alert">×</a>
				{{ message }}
			</div>
		{% endfor %}
	</div>
{% endif %}

<nav class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'home_page' %}">Академия джедаев</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li><a href="{% url 'academy:candidate-new' %}">Для кандидатов</a></li>
				<li><a href="{% url 'academy:jedi-list' %}">Для джедаев</a></li>
			</ul>
		</div>
	</div>
</nav>

<div class="container">

	<div class="row row-offcanvas row-offcanvas-right">
		{% block content %}

		{% endblock %}
	</div>

	<hr>
	<footer>
		<p>&copy; 2016 Company, Inc.</p>
	</footer>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>

</body>
</html>

apps/templates/home.html
{% extends 'base.html' %}

{% block content %}
	<div class="col-xs-12 col-sm-9">

		<div class="jumbotron">
			<h1>Добро пожаловать в Академию Джедаев!</h1>
		</div>
	</div>
	<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
		<div class="list-group">
			<a href="#" class="list-group-item active">Link</a>
			<a href="#" class="list-group-item">Link</a>
			<a href="#" class="list-group-item">Link</a>
			<a href="#" class="list-group-item">Link</a>
		</div>
	</div>
{% endblock %}