apps/academy/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^candidate/$', views.CandidateCreateView.as_view(), name='candidate-new'),

    url(r'^test-list/$', views.TestTestListView.as_view(), name='test-list'),

    url(r'^test/(?P<slug>[a-z0-9_-]+)/$', views.test_detail_view, name='test-detail'),

    url(r'^jedi/$', views.JediListView.as_view(), name='jedi-list'),

    url(r'^candidate/list/(?P<jedi_pk>\d+)/$', views.candidate_list, name='candidate-list'),

    url(r'^candidate/add/$', views.candidate_add, name='candidate-add'),
]

apps/core/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'academy/', include('academy.urls', namespace='academy')),

    url(r'^$', views.HomePage.as_view(), name='home_page'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

apps/academy/models.py
from django.db import models
from django.urls import reverse


class Planet(models.Model):
    """ Планета """
    name = models.CharField('Наименование', max_length=100, unique=True)

    class Meta:
        verbose_name = 'Планета'
        verbose_name_plural = 'Планеты'

    def __str__(self):
        return self.name


class Jedi(models.Model):
    """ Джедай """
    name = models.CharField('Имя', max_length=20, unique=True)
    planet = models.ForeignKey(Planet)

    class Meta:
        verbose_name = 'Джедай'
        verbose_name_plural = 'Джедаи'
        ordering = ['-id']

    def __str__(self):
        return '{} / {}'.format(self.name, self.planet)

    @property
    def padavan_count(self):
        """ Количество подаванов в обучении """
        return Candidate.objects.filter(mentor=self).count()


class Candidate(models.Model):
    """ Кандидат """
    name = models.CharField('Имя', max_length=20)
    planet = models.ForeignKey(Planet)
    age = models.PositiveSmallIntegerField('Возраст',  help_text='Укажите сколько вам полных лет.')
    email = models.EmailField('Email', max_length=30, unique=True)
    mentor = models.ForeignKey(Jedi, null=True, blank=True)

    class Meta:
        verbose_name = 'Кандидат'
        verbose_name_plural = 'Кандидаты'
        ordering = ['-id']

    def __str__(self):
        return '{} / {} / {}'.format(self.name, self.planet, self.email)


class TestTest(models.Model):
    """ Тестовое испытание """
    name = models.CharField('Название испытания', max_length=100)
    slug = models.SlugField('Код ордена', unique=True, max_length=100)

    class Meta:
        verbose_name = 'Тестовое испытание'
        verbose_name_plural = 'Тестовые испытания'
        ordering = ['-id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('academy:test-detail', args=[self.slug])


class Question(models.Model):
    """ Вопрос """
    test_test = models.ForeignKey(TestTest)
    question_text = models.CharField('Вопрос', max_length=200)

    def __str__(self):
        return self.question_text

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class Choice(models.Model):
    """ Вариант ответа """
    question = models.ForeignKey(Question)
    choice_text = models.CharField('Вариант ответа', max_length=200)
    votes = models.IntegerField('Количество баллов', default=0)

    def __str__(self):
        return self.choice_text

    class Meta:
        verbose_name = 'Вариант ответа'
        verbose_name_plural = 'Варианты ответа'


class TestResult(models.Model):
    """ результат испытания """
    candidate = models.ForeignKey(Candidate)
    test = models.ForeignKey(TestTest)
    complete = models.BooleanField('Задание пройдено', default=False)
    points = models.PositiveSmallIntegerField('Количество баллов')

    def __str__(self):
        return '{} / {}'.format(self.candidate, self.test)

    class Meta:
        verbose_name = 'Результат'
        verbose_name_plural = 'Результаты'
        ordering = ['-id']


class TestResultAnswer(models.Model):
    """ Ответ на вопрос испытания """
    test = models.ForeignKey(TestResult)
    question = models.ForeignKey(Question)
    choice = models.ForeignKey(Choice)

    def __str__(self):
        return '{} / {}'.format(self.question, self.choice)

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

apps/templates/pages/candidate-list.html
{% extends 'base.html' %}

{% block content %}
	<div class="col-xs-12 col-sm-9">
		<h2>Список кандидатов</h2>

		{% for candidate in candidates %}
			<form action="{% url 'academy:candidate-add' %}" method="post">
				{% csrf_token %}
				<input name="jedi" type="hidden" value="{{ jedi }}">
				<input name="candidate" type="hidden" value="{{ candidate.id }}">
				{{ candidate.name }}
				<ol>
					{% for test in candidate.testresult_set.all %}
						<li>
							{{ test.test.name }}
							<ul>
								{% for answer in test.testresultanswer_set.all %}
									<li>
										{{ answer.question.question_text }} - {{ answer.choice.choice_text }} ({{ answer.choice.votes }})
									</li>
								{% endfor %}
							</ul>
						</li>
					{% endfor %}
				</ol>
				<input type="submit" value="Зачислить">
			</form>

		{% endfor %}
	</div>
{% endblock %}

apps/templates/pages/candidate-new.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
	<div class="col-xs-12 col-sm-9">
		<form action="{% url 'academy:candidate-new' %}" method="post">
			{% csrf_token %}
			{% bootstrap_form form %}

			<input type="submit" value="Далее">
		</form>
	</div>
{% endblock %}

apps/templates/pages/jedi-list.html
{% extends 'base.html' %}

{% block content %}
	<div class="col-xs-12 col-sm-9">
		<h2>Выберите джедая</h2>

		<ul>
			{% for jedi in jedi_all %}
				<li><a href="{% url 'academy:candidate-list' jedi.id %}">{{ jedi.name }} ({{ jedi.padavan_count }})</a></li>
			{% endfor %}
		</ul>


		{% if jedi_count %}
			<hr>
			<ol>
				{% for jedi in jedi_count %}
					<li><a href="{% url 'academy:candidate-list' jedi.id %}">{{ jedi.name }} ({{ jedi.padavan_count }})</a></li>
				{% endfor %}

			</ol>
		{% endif %}

	</div>
{% endblock %}

apps/templates/pages/test-detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
	<div class="col-xs-12 col-sm-9">

		<h2>{{ item.name }}</h2>

		<form action="{% url 'academy:test-detail' item.slug %}" method="post" class="form-horizontal">
			{% csrf_token %}
			<input type="hidden" name="testtest" value="{{ item.id }}">
			{% for question in item.question_set.all %}
				<div class="form-group">
					<label class="col-sm-2 control-label">{{ question.question_text }}</label>
					<div class="col-sm-10">
						{% for choises in question.choice_set.all %}
							<div class="radio">
								<label>
									<input type="radio" name="question-{{ question.id }}" value="{{ choises.id }}" required>
									{{ choises.choice_text }}
								</label>
							</div>
						{% endfor %}
					</div>
				</div>
			{% endfor %}
			<input type="submit" class="btn btn-default" value="Закончить">
		</form>

	</div>
{% endblock %}

apps/templates/pages/test-list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
	<div class="col-xs-12 col-sm-9">
		{% if items %}
			<ul>
				{% for test in items %}
					<li><a href="{{ test.get_absolute_url }}">{{ test.name }}</a></li>
				{% endfor %}
			</ul>
		{% else %}
			<p>Нет доступных испытаний.</p>
		{% endif %}
	</div>
{% endblock %}

apps/templates/pages/test-result.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
	<div class="col-xs-12 col-sm-9">

		<h2>Резултат</h2>
		{{ question }}

		<pre>
			{{ post }}
		</pre>

	</div>
{% endblock %}